export const SET_LOADING_ENTRIES = 'SET_LOADING_ENTRIES';
export const SET_ENTRIES = 'SET_ENTRIES';
export const SET_NEXT_ENTRIES = 'SET_NEXT_ENTRIES';
export const GET_ENTRIES_SUCCESS = 'GET_ENTRIES_SUCCESS';
export const GET_ENTRIES_ERROR = 'GET_ENTRIES_ERROR';
